In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn import preprocessing
import matplotlib.pylab as plt

In [3]:
wine = pd.read_csv("Wine.csv")

In [4]:
wine

,Type,Alcohol,Malic_Acid,Ash,Ash_Alcalinity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0,A,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,A,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,A,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,A,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,A,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,C,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,C,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,C,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,C,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,C,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [6]:
wine = wine.drop('Type',axis=1)
wine.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcalinity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [7]:
pca = PCA()
pca.fit(preprocessing.scale(wine))

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [8]:
pcs = PCA(n_components=2)
pcs.fit(wine[["Malic_Acid", "Ash_Alcalinity"]])

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [10]:
pcsSummary = pd.DataFrame({"Standard deviation":np.sqrt(pcs.explained_variance_),"Proportion of variance": pcs.explained_variance_ratio_,
"Cumulative proportion": np.cumsum(pcs.explained_variance_ratio_)})

In [11]:
pcsSummary

   Standard deviation  Proportion of variance  Cumulative proportion
0            3.356829                0.908683               0.908683
1            1.064143                0.091317               1.000000

In [12]:
pcsSummary= pcsSummary.transpose()
pcsSummary

                               0         1
Standard deviation      3.356829  1.064143
Proportion of variance  0.908683  0.091317
Cumulative proportion   0.908683  1.000000

In [14]:
pcsSummary.columns = ["PC2", "PC1"]
pcsSummary.columns

Index(['PC2', 'PC1'], dtype='object')

In [15]:
pcs.components_

array([[ 0.10680091,  0.99428043],
       [ 0.99428043, -0.10680091]])

In [16]:
weights = pd.DataFrame(pcs.transform(wine[["Malic_Acid", "Ash_Alcalinity"]]),columns=["PC1", "PC2"])
weights

          PC1       PC2
0   -3.939561 -0.206782
1   -8.306919  0.332741
2   -0.887299  0.119097
3   -2.720792 -0.096316
4    1.523538  0.091460
..        ...       ...
173  1.353209  3.187358
174  3.653076  1.190308
175  0.709751  1.878594
176  0.529258  0.198260
177  5.164789  1.219020

[178 rows x 2 columns]

In [17]:
weights['PC2']

0     -0.206782
1      0.332741
2      0.119097
3     -0.096316
4      0.091460
         ...
173    3.187358
174    1.190308
175    1.878594
176    0.198260
177    1.219020
Name: PC2, Length: 178, dtype: float64

In [18]:
wine['Malic_Acid'].mean()

2.3363483146067416

In [19]:
pcs = PCA(n_components=13)
pcs.fit(wine)

PCA(copy=True, iterated_power='auto', n_components=13, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [20]:
pcsSummary_df = pd.DataFrame({"Std devn":np.sqrt(pcs.explained_variance_),"Proportion of var": pcs.explained_variance_ratio_,
"Cum proportion": np.cumsum(pcs.explained_variance_ratio_)})
pcsSummary_df

      Std devn  Proportion of var  Cum proportion
0   314.963156       9.980912e-01        0.998091
1    13.135268       1.735916e-03        0.999827
2     3.072151       9.495896e-05        0.999922
3     2.234095       5.021736e-05        0.999972
4     1.108533       1.236368e-05        0.999985
5     0.917095       8.462130e-06        0.999993
6     0.528179       2.806815e-06        0.999996
7     0.389077       1.523081e-06        0.999997
8     0.334809       1.127830e-06        0.999999
9     0.267773       7.214158e-07        0.999999
10    0.193845       3.780603e-07        1.000000
11    0.145163       2.120138e-07        1.000000
12    0.090574       8.253928e-08        1.000000

In [21]:
pcsSummary_df.columns = ["PC".format(i) for i in range(1, len(pcsSummary_df.columns) + 1)]
pcsSummary_df.round(4)

          PC      PC      PC
0   314.9632  0.9981  0.9981
1    13.1353  0.0017  0.9998
2     3.0722  0.0001  0.9999
3     2.2341  0.0001  1.0000
4     1.1085  0.0000  1.0000
5     0.9171  0.0000  1.0000
6     0.5282  0.0000  1.0000
7     0.3891  0.0000  1.0000
8     0.3348  0.0000  1.0000
9     0.2678  0.0000  1.0000
10    0.1938  0.0000  1.0000
11    0.1452  0.0000  1.0000
12    0.0906  0.0000  1.0000

In [23]:
pcs = PCA()
pcs.fit(preprocessing.scale(wine))

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [24]:
pcsSummary_df = pd.DataFrame({"Std devn":np.sqrt(pcs.explained_variance_),"Proportion of var": pcs.explained_variance_ratio_,
"Cum proportion": np.cumsum(pcs.explained_variance_ratio_)})
pcsSummary_df

    Std devn  Proportion of var  Cum proportion
0   2.175417           0.361988        0.361988
1   1.584639           0.192075        0.554063
2   1.205920           0.111236        0.665300
3   0.961335           0.070690        0.735990
4   0.926309           0.065633        0.801623
5   0.803295           0.049358        0.850981
6   0.744407           0.042387        0.893368
7   0.592002           0.026807        0.920175
8   0.538992           0.022222        0.942397
9   0.502315           0.019300        0.961697
10  0.476513           0.017368        0.979066
11  0.411975           0.012982        0.992048
12  0.322431           0.007952        1.000000

In [25]:
pcsSummary_df.columns = ["PC".format(i) for i in range(1, len(pcsSummary_df.columns) + 1)]
pcsSummary_df.round(3)

       PC     PC     PC
0   2.175  0.362  0.362
1   1.585  0.192  0.554
2   1.206  0.111  0.665
3   0.961  0.071  0.736
4   0.926  0.066  0.802
5   0.803  0.049  0.851
6   0.744  0.042  0.893
7   0.592  0.027  0.920
8   0.539  0.022  0.942
9   0.502  0.019  0.962
10  0.477  0.017  0.979
11  0.412  0.013  0.992
12  0.322  0.008  1.000